# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wowCS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_content',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='notebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wowCS.Notebook'),
        ),
    ]
