# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowCS', '0005_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_content',
            field=models.TextField(),
        ),
    ]
