# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowCS', '0006_auto_20170223_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='notebook_title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
