# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowCS', '0009_auto_20170224_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='genre',
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
