# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 04:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wowCS', '0012_auto_20170225_0338'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([('user', 'favorite_id')]),
        ),
    ]
